# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncard.proto\"\x13\n\x11\x43reateCardRequest\")\n\x12\x43reateCardResponse\x12\x13\n\x04\x63\x61rd\x18\x01 \x01(\x0b\x32\x05.Card\" \n\x04\x43\x61rd\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x11\n\x0fGetCardsRequest\"(\n\x10GetCardsResponse\x12\x14\n\x05\x63\x61rds\x18\x01 \x03(\x0b\x32\x05.Card2y\n\x0b\x43\x61rdService\x12\x37\n\nCreateCard\x12\x12.CreateCardRequest\x1a\x13.CreateCardResponse\"\x00\x12\x31\n\x08GetCards\x12\x10.GetCardsRequest\x1a\x11.GetCardsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'card_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREATECARDREQUEST']._serialized_start=14
  _globals['_CREATECARDREQUEST']._serialized_end=33
  _globals['_CREATECARDRESPONSE']._serialized_start=35
  _globals['_CREATECARDRESPONSE']._serialized_end=76
  _globals['_CARD']._serialized_start=78
  _globals['_CARD']._serialized_end=110
  _globals['_GETCARDSREQUEST']._serialized_start=112
  _globals['_GETCARDSREQUEST']._serialized_end=129
  _globals['_GETCARDSRESPONSE']._serialized_start=131
  _globals['_GETCARDSRESPONSE']._serialized_end=171
  _globals['_CARDSERVICE']._serialized_start=173
  _globals['_CARDSERVICE']._serialized_end=294
# @@protoc_insertion_point(module_scope)
